### PR TITLE
change_Nifty_text

### PR DESCRIPTION
**Pull request by vfa-tamhh**
+ Change ニフティクラウドmobile backend to ニフクラ mobile backend.
+ Change NIFTYCloud to NIFCloud.
+ Change some text on images.

### CODE REVIEW

**Comment by vfa-duyna** [comment]
@vfa-tamhh
Still contains `Nifty`:
https://github.com/vfa-tamhh/AndroidImageViewApp/blob/change_Nifty_text/readme-img/009.png

**Comment by vfa-duyna** [comment]
@vfa-tamhh
Readme still contains `Nifty`:
```
new AlertDialog.Builder(MainActivity.this)
                             .setTitle("Notification from Nifty")
```

**Comment by vfa-tamhh** [comment]
> @vfa-tamhh
> Still contains Nifty:
> https://github.com/vfa-tamhh/AndroidImageViewApp/blob/change_Nifty_text/readme-img/009.png
> 
> @vfa-tamhh
> Readme still contains Nifty:
> 
> new AlertDialog.Builder(MainActivity.this)
>                              .setTitle("Notification from Nifty")

Updated. Change image and code.

**Comment by vfa-duyna** [comment]
@vfa-tamhh 
I confirmed OK.

**Pull request merged**
